version: "3.7"
services:
  jenkins:
    image: writio/jenkins:${WRITIO_VERSION}
    container_name: "${COMPOSE_PROJECT_NAME}_jenkins"
    restart: unless-stopped
    user: root
    environment:
      - "MAVEN_VOLUME=${COMPOSE_PROJECT_NAME}_maven_repository"
      - "WRITIO_GITHUB_USER=<...>"
      - "WRITIO_GITHUB_SECRET=<...>"
      - "WRITIO_DOCKERHUB_USER=<...>"
      - "WRITIO_DOCKERHUB_SECRET=<...>"
      - "JENKINS_USER=<...>"
      - "JENKINS_PASS=<...>"
    volumes:
      - type: bind
        source: "./jenkins.yaml"
        target: "/usr/share/jenkins/ref/jenkins.yaml"
      - type: bind
        source: "./jobs"
        target: "/usr/share/jenkins/ref/jobs"
      - type: bind
        source: "${LOCAL_CONTAINER_ENGINE_SOCKET}"
        target: "/var/run/docker.sock"
      - type: bind
        source: "./.."
        target: "/var/jenkins_home/jobs/writio-build-local/workspace"
      - type: volume
        source: maven_repository
        target: /root/.m2/repository
    ports:
      - "${LOCAL_JENKINS_PORT}:8080"
      - "50000:50000"
volumes:
  maven_repository: