version: "3.7"

services:

  jenkins:
    build:
      context: ./docker/jenkins
      dockerfile: Dockerfile
    image: writio/jenkins:latest
    container_name: writio_ci_jenkins
    restart: unless-stopped
    user: root
    environment:
      - MAVEN_VOLUME=writio_ci_maven_repository
    volumes:
      - type: bind
        source: ./jobs
        target: /var/jenkins_home/jobs
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    ports:
      - "48081:8080"
      - "50000:50000"
  
  filebrowser:
    build:
      context: ./docker/filebrowser
      dockerfile: Dockerfile
    image: writio/filebrowser:latest
    container_name: writio_ci_filebrowser
    restart: unless-stopped
    volumes:
      - type: volume
        source: maven_repository
        target: /srv/maven_repository
      - type: volume
        source: jenkins_data
        target: /srv/jenkins
    ports:
      - 48080:80

  maven:
    build:
      context: ./docker/maven
      dockerfile: Dockerfile
    image: writio/maven:latest
    container_name: writio_ci_maven
  
volumes:
  jenkins_data:
  maven_repository: