version: "3.7"

services:

  jenkins:
    depends_on:
      - maven_repository_init
    build:
      context: ./docker/jenkins
      dockerfile: Dockerfile
    image: writio/jenkins:latest
    container_name: writio_ci_jenkins
    restart: unless-stopped
    user: root
    volumes:
      - type: bind
        source: ./jobs
        target: /var/jenkins_home/jobs
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    #  - type: volume
    #    source: jenkins_data
    #    target: /var/jenkins_home
      - type: volume
        source: maven_data
        target: /root
    ports:
      - "48081:8080"
      - "50000:50000"
  
  filebrowser:
    build:
      context: ./docker/filebrowser
      dockerfile: Dockerfile
    image: writio/filebrowser:latest
    container_name: writio_ci_filebrowser
    restart: unless-stopped
    volumes:
      - type: volume
        source: maven_data
        target: /srv/maven
      - type: volume
        source: jenkins_data
        target: /srv/jenkins
    ports:
      - 48080:80
  
  maven_repository_init:
    build:
      context: ./docker/maven
      dockerfile: Dockerfile
    image: writio/maven:latest
    volumes:
      - type: volume
        source: maven_data
        target: /volume
    command: ["cp", "-r", "/root/.m2", "/volume"]
  
volumes:
  jenkins_data:
  maven_data: