jenkins:
  numExecutors: 1
tool:
  git:
    installations:
    - home: "git"
      name: "Default"
jobs:
  - file: "${REF}/jobs/writio-build-branch/config.groovy"
  - file: "${REF}/jobs/writio-build-local/config.groovy"