jenkins:
  systemMessage: "writio jenkins\n\n"
  numExecutors: 1
tool:
  git:
    installations:
    - home: "git"
      name: "Default"
jobs:
  - file: "${REF}/jobs/writio-build-branch/config.groovy"
  - file: "${REF}/jobs/writio-build-local/config.groovy"
  - file: "${REF}/jobs/writio-release-branch/config.groovy"
credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: "writio-github-credential"
              username: ${WRITIO_GITHUB_USER}
              password: ${WRITIO_GITHUB_SECRET}
              description: "writio github credential"
          - usernamePassword:
              scope: GLOBAL
              id: "writio-dockerhub-credential"
              username: ${WRITIO_DOCKERHUB_USER}
              password: ${WRITIO_DOCKERHUB_SECRET}
              description: "writio dockerhub credential"
unclassified:
  location:
    url: "http://localhost:48080/"
  simple-theme-plugin:
    elements:
      - cssUrl: 
          url: "http://localhost:48080/userContent/writio.css"
  globalConfigFiles:
    configs:
      - json:
          id: writio-config
          name: writio config
          comment: writio config
          content: |
            {
                "repositoryUrl": "https://github.com/cbehrenberg/writio.git",
                "authRepositoryUrl": "https://<credential>@github.com/cbehrenberg/writio.git"
            }